"use client";

import { Shield } from "lucide-react";

interface SafetyScoreGaugeProps {
  score: number;
  gradientUsed?: boolean;
  rounds?: number;
}

function getScoreColors(score: number): {
  stroke: string;
  text: string;
  glow: string;
  status: string;
} {
  if (score >= 90)
    return {
      stroke: "#22c55e",
      text: "text-emerald-400",
      glow: "shadow-[0_0_28px_rgba(34,197,94,0.18)]",
      status: "Healthy posture",
    };
  if (score >= 70)
    return {
      stroke: "#f59e0b",
      text: "text-amber-400",
      glow: "shadow-[0_0_28px_rgba(245,158,11,0.18)]",
      status: "Moderate risk",
    };
  return {
    stroke: "#ef4444",
    text: "text-red-400",
    glow: "shadow-[0_0_28px_rgba(239,68,68,0.18)]",
    status: "High vulnerability risk",
  };
}

export default function SafetyScoreGauge({ score, gradientUsed, rounds }: SafetyScoreGaugeProps) {
  const clamped = Math.min(100, Math.max(0, score));
  const colors = getScoreColors(score);
  const circumference = 2 * Math.PI * 42;
  const strokeOffset = circumference - (clamped / 100) * circumference;

  return (
    <section className="rounded-xl border border-white/10 bg-white/5 backdrop-blur-md p-4 sm:p-5 transition-all duration-300 shadow-lg shadow-black/20 hover-lift h-full min-h-[180px] flex flex-col">
      <div className="flex items-center gap-2 mb-0.5">
        <Shield className="w-4 h-4 text-zinc-500" />
        <span className="text-xs font-medium uppercase tracking-widest text-zinc-500">
          Security Report
        </span>
      </div>
      <p className="text-xs text-zinc-600 mb-2">Security posture summary</p>
      {gradientUsed && (
        <p className="text-xs font-medium text-indigo-400/90 mb-2 rounded-md bg-indigo-500/10 border border-indigo-500/20 inline-block px-2.5 py-1">
          Adversarial attacks generated by DigitalOcean Gradient&trade; AI
        </p>
      )}
      <div className="flex flex-col sm:flex-row items-center gap-3 sm:gap-5 flex-1">
        <div className={`relative flex-shrink-0 ${colors.glow} rounded-full p-1`}>
          <svg className="w-28 h-28 -rotate-90" viewBox="0 0 100 100">
            <circle
              cx="50"
              cy="50"
              r="42"
              fill="none"
              stroke="currentColor"
              strokeWidth="10"
              className="text-white/5"
            />
            <circle
              cx="50"
              cy="50"
              r="42"
              fill="none"
              stroke={colors.stroke}
              strokeWidth="10"
              strokeLinecap="round"
              strokeDasharray={circumference}
              strokeDashoffset={strokeOffset}
              className="transition-all duration-700 ease-out"
            />
          </svg>
          <span className={`absolute inset-0 flex items-center justify-center text-3xl font-bold tabular-nums ${colors.text}`}>
            {clamped}
          </span>
        </div>
        <div className="text-center sm:text-left space-y-0.5">
          <p className="text-xl sm:text-2xl font-bold text-zinc-100 tracking-tight">
            Global Safety Score
          </p>
          <p className="text-zinc-500 text-xs">out of 100</p>
          <p className={`text-sm font-medium pt-1 ${colors.text}`}>
            {colors.status}
          </p>
          {rounds !== undefined && rounds > 1 && (
            <p className="text-xs text-indigo-400/80 pt-0.5">
              Tested across {rounds} rounds (adaptive refinement)
            </p>
          )}
        </div>
      </div>
    </section>
  );
}
