import { render, screen } from "@testing-library/react";
import SafetyScoreGauge from "@/components/SafetyScoreGauge";

describe("SafetyScoreGauge", () => {
  it("renders the score value", () => {
    render(<SafetyScoreGauge score={85} />);
    expect(screen.getByText("85")).toBeInTheDocument();
  });

  it("shows Security Report heading", () => {
    render(<SafetyScoreGauge score={50} />);
    expect(screen.getByText("Security Report")).toBeInTheDocument();
  });

  it("shows Global Safety Score label", () => {
    render(<SafetyScoreGauge score={70} />);
    expect(screen.getByText("Global Safety Score")).toBeInTheDocument();
  });

  it("shows Healthy posture for score >= 90", () => {
    render(<SafetyScoreGauge score={92} />);
    expect(screen.getByText("Healthy posture")).toBeInTheDocument();
  });

  it("shows Moderate risk for score >= 70 and < 90", () => {
    render(<SafetyScoreGauge score={75} />);
    expect(screen.getByText("Moderate risk")).toBeInTheDocument();
  });

  it("shows High vulnerability risk for score < 70", () => {
    render(<SafetyScoreGauge score={40} />);
    expect(screen.getByText("High vulnerability risk")).toBeInTheDocument();
  });

  it("displays Gradient AI badge when gradientUsed is true", () => {
    render(<SafetyScoreGauge score={80} gradientUsed={true} />);
    expect(
      screen.getByText(/Adversarial attacks generated by DigitalOcean Gradient™ AI/i)
    ).toBeInTheDocument();
  });

  it("does not display Gradient badge when gradientUsed is false", () => {
    render(<SafetyScoreGauge score={80} gradientUsed={false} />);
    expect(
      screen.queryByText(/Adversarial attacks generated by DigitalOcean Gradient™ AI/i)
    ).not.toBeInTheDocument();
  });

  it("clamps score between 0 and 100", () => {
    const { rerender } = render(<SafetyScoreGauge score={150} />);
    expect(screen.getByText("100")).toBeInTheDocument();
    rerender(<SafetyScoreGauge score={-10} />);
    expect(screen.getByText("0")).toBeInTheDocument();
  });
});
